config/routes.rb
Key2::Application.routes.draw do
  get "static_pages/home"
  resources :for_selects
  resources :keys

  root 'static_pages#home'

end

app/models/for_select.rb
class ForSelect < ActiveRecord::Base

	# Create a 2d array to be used in "grouped_options_for_select" in "select-tag"
	# "db_model" is the name of the model containing all the select information
	# "code" is the value in the code field in the db_model that identifies
		# which group of values will appear in the grouped select
	# "grouped_options" is my gem which generates the 2d array
		# gem 'grouped_options', git: 'git@github.com:marcmentis/grouped_options.git'
	def self.GroupedSelect(facility, code, db_model)
		@forSelect = db_model.all
					  .where(facility: facility)
                      .where(code: code)
                      .order(option_order: :asc)  
	    # @grouped_options = ForSelect.grouped_options(@forSelect)
	    @grouped_options = GroupedOptions.grouped_options(@forSelect)
		
	end

	def self.CollectionForSelect(facility, code, db_model)
		select_collection = db_model.where(facility: facility)
									.where(code: code)
									.order(option_order: :asc)
	end
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Pundit
  
end

app/controllers/for_selects_controller.rb
class ForSelectsController < ApplicationController
  before_action :set_for_select, only: [:show, :edit, :update, :destroy]

  # GET /for_selects
  # GET /for_selects.json
  def index
    # byebug
    # @for_selects = ForSelect.all
    #session[:facility] = "0038"
    @q = ForSelect.search(params[:q])
    @for_selects = @q.result.page(params[:page]).per(15)

    @totNumber = ForSelect.all.count
    @searchNumber = @q.result.count
  end

  # GET /for_selects/1
  # GET /for_selects/1.json
  def show
  end

  # GET /for_selects/new
  def new
    @for_select = ForSelect.new
    # Generate the 2d array needed for grouped select in view
    @grouped_options = ForSelect.GroupedSelect('9999','facility', ForSelect)
 end

  # GET /for_selects/1/edit
  def edit
    # Generate the 2d array needed for grouped select in view
    @grouped_options = ForSelect.GroupedSelect('9999','facility', ForSelect)
 end

  # POST /for_selects
  # POST /for_selects.json
  def create
    @for_select = ForSelect.new(for_select_params)

    respond_to do |format|
      if @for_select.save
        format.html { redirect_to @for_select, notice: 'For select was successfully created.' }
        format.json { render action: 'show', status: :created, location: @for_select }
      else
        format.html { render action: 'new' }
        format.json { render json: @for_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /for_selects/1
  # PATCH/PUT /for_selects/1.json
  def update
    respond_to do |format|
      if @for_select.update(for_select_params)
        format.html { redirect_to @for_select, notice: 'For select was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @for_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /for_selects/1
  # DELETE /for_selects/1.json
  def destroy
    @for_select.destroy
    respond_to do |format|
      format.html { redirect_to for_selects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_for_select
      @for_select = ForSelect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def for_select_params
      params.require(:for_select).permit(:code, :value, :text, :grouper, :option_order, :facility)
    end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  before_action :set_key, only: [:show, :edit, :update, :destroy]

   # GET /keys
  # GET /keys.json
  def index
    #@keys = Key.all
    # Get keys for ransack
    fac_keys = Key.where('facility = ?', session[:facility])
    @q = fac_keys.search(params[:q]) 
    @keys = @q.result.page(params[:page]).per(15)

    # @totNumber = Key.all.count
    @totNumber = fac_keys.count
    @searchNumber = @q.result.count  
  
    # Generate the 2d array needed for grouped select in view
    @grouped_options = ForSelect.GroupedSelect(session[:facility], 'company', ForSelect) 
    @grouped_options2 = ForSelect.GroupedSelect('9999','facility', ForSelect)

    respond_to do |format|
      format.html { render action: 'index' }
      format.js {}
    end
 end

  # GET /keys/1
  # GET /keys/1.json
  def show
  end

  # GET /keys/new
  def new
    @key = Key.new
    #session[:facility] = '0038'

    # Generate the 2d array needed for grouped select in view
    @grouped_options = ForSelect.GroupedSelect(session[:facility],'company', ForSelect) 
    @grouped_options2 = ForSelect.GroupedSelect('9999','facility', ForSelect)

    respond_to do |format|
      format.html { render action: 'new' }
      format.js { render "new_edit" }
    end
   end

  # GET /keys/1/edit
  def edit
     # Generate the 2d array needed for grouped select in view
    @grouped_options = ForSelect.GroupedSelect(session[:facility],'company', ForSelect) 
    @grouped_options2 = ForSelect.GroupedSelect('9999','facility', ForSelect)

    respond_to do |format|
      format.html { render action: 'edit' }
      format.js { render "new_edit" }
    end
  end

  # POST /keys
  # POST /keys.json
  def create
    @key = Key.new(key_params)

    respond_to do |format|
      if @key.save
        format.html { redirect_to @key, notice: 'Key was successfully created.' }
        format.js {render "update_create"}
        format.json { render action: 'show', status: :created, location: @key }
      else
        format.html { render action: 'new' }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keys/1
  # PATCH/PUT /keys/1.json
  def update
    respond_to do |format|
      if @key.update(key_params)
        @q = Key.search(params[:q])
        @keys = @q.result.page(params[:page]).per(15)

        if session[:role] == 'admin2'
          @q = Key.search(params[:q])  
          @keys = @q.result.page(params[:page]).per(15)
          # @totNumber = Key.all.count
          # @searchNumber = @q.result.count     
        else 
          # Get keys for ransack
          #session[:facility] = '0038'
          fac_keys = Key.where('facility = ?', session[:facility])
          @q = fac_keys.search(params[:q]) 
          @keys = @q.result.page(params[:page]).per(15)
          # @totNumber = fac_keys.count
          # @searchNumber = @q.result.count  
        end

        format.html { redirect_to @key, notice: 'Key was successfully updated.' }
        format.js { render "update_create" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key.destroy
    respond_to do |format|
      format.html { redirect_to keys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_key
      @key = Key.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def key_params
      params.require(:key).permit(:description, :number, :facility, :company, :checkout, :checkin)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	# Get 'request' and 'response' objects from Authentication system
  	@request = request

    session[:facility] = "0038"  # Hack as "Skill" repo doesn't contain User table nor set session variables properly
    session[:role] = "admin2"
  
  	# Raise exception if browser not chrome
  	begin
    	raise RuntimeError unless @request.headers["HTTP_USER_AGENT"].downcase.include? "chrome"
    	rescue RuntimeError
      render file: "#{Rails.root}/public/browser_error", layout: false
  	end

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/for_selects_helper.rb
module ForSelectsHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/for_selects/_form.html.erb
<%= form_for(@for_select) do |f| %>
  <% if @for_select.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@for_select.errors.count, "error") %> prohibited this for_select from being saved:</h2>

      <ul>
      <% @for_select.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="large-3 columns panel radius">
    <div class="panel callout radius">
      <div>
        <%= f.label :code %>
        <%= f.text_field :code %>
      </div>
      <div>
        <%= f.label :value %>
        <%= f.text_field :value %>
      </div>
      <div>
        <%= f.label :text %>
        <%= f.text_field :text %>
      </div>
      <div>
        <%= f.label :grouper %>
        <%= f.text_field :grouper %>
      </div>
      <div>
        <%= f.label :option_order %>
        <%= f.number_field :option_order %>
      </div>
      <div>
        <%= f.label :facility %>
        <%#= f.text_field :facility %>
        <%#= f.select(:facility, grouped_options_for_select(@grouped_options), prompt: 'Choose Facility') %>
        <%= select_tag(:sFor_select_facility, grouped_options_for_select(@grouped_options), prompt: 'Please Select') %>
      </div>
      <div>
        <%= f.submit class: "button tiny radius"%>
      </div>
    </div>
    
  </div>
</div>
<% end %>

app/views/for_selects/edit.html.erb
<h1>Editing for_select</h1>

<%= render 'form' %>

<%= link_to 'Show', @for_select %> |
<%= link_to 'Back', for_selects_path %>

app/views/for_selects/index.html.erb
<div class="row">
  <div class="large-5 columns large-offset-3 ">
      <h3>Listing of Selections</h3>
  </div>

</div>
<div class="row">
  <div class="large-9 columns">
    <div class="panel radius">

      <div class="panel callout radius">
        <%= search_form_for @q, id: 'fFor_select_filter' do |f| %>
        <div class="row collapse">
          <div class="hide">
            <div class="small-2 columns">
              <%= f.submit class: 'button tiny radius' %>
            </div>
          </div>
          <div class="small-12 columns">
            <div class="row collapse">
              <div class="small-1 columns">
                <%= f.label(:code_start, 'Code:', class: "right inline") %>
              </div>
              <div class="small-2 columns end">
                <%= f.search_field :code_start %>
              </div>
              <div class="small-2 columns">
                <%= f.label(:facility_eq, 'Facility:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :facility_eq %>
              </div> 
              <div class="small-2 columns">
                <%= f.label(:value_start, 'Value:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :value_start %>
              </div>   
           </div> 

            <div class="row collapse">
               <div class="small-1 columns">
                <%= f.label(:text_start, 'Text:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :text_start %>
              </div> 
              <div class="small-2 columns">
                <%= f.label(:grouper_start, 'Grouper:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :grouper_start %>
              </div> 
              <div class="small-2 columns">
                <%= f.label(:option_order_eq, 'Order:', class: "right inline") %>
              </div>
              <div class="small-2 left columns">
                <%= f.search_field :option_order_eq %>
              </div> 
            </div>

          </div>
        </div>         
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="large-9 columns">
    <div class="panel radius">

<table>
  <thead>
    <tr class="tableHeader">
      <th><%= sort_link(@q, :code, "Code") %></th>
      <th><%= sort_link(@q, :value, "Value") %></th>
      <th><%= sort_link(@q, :text, "Text") %></th>
      <th><%= sort_link(@q, :grouper, "Grouper") %></th>
      <th><%= sort_link(@q, :option_order, "Order") %></th>
      <th><%= sort_link(@q, :facility, "Facility") %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @for_selects.each do |for_select| %>
      <tr>
        <td><%= for_select.code %></td>
        <td><%= for_select.value %></td>
        <td><%= for_select.text %></td>
        <td><%= for_select.grouper %></td>
        <td><%= for_select.option_order %></td>
        <td><%= for_select.facility %></td>
        <td><%= link_to 'Show', for_select %></td>
        <td><%= link_to 'Edit', edit_for_select_path(for_select) %></td>
        <td><%= link_to 'Destroy', for_select, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="5" class="tableFooter">
        <%= paginate @for_selects %>
      </td>
      <td colspan="4" class="tableFooter">
         <%= @searchNumber %> from <%= @totNumber %>
      </td>
    </tr>
  </tbody>
</table>
    </div>
  </div>
</div>

<br>

<%= link_to 'New For select', new_for_select_path, class: "button tiny radius" %>

app/views/for_selects/new.html.erb
<h1>New Selection</h1>

<%= render 'form' %>

<%= link_to 'Back', for_selects_path %>

app/views/for_selects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="large-3 columns panel radius">
    <div class="panel callout radius">
      <p>
        <strong>Code:</strong>
        <%= @for_select.code %>
      </p>

      <p>
        <strong>Value:</strong>
        <%= @for_select.value %>
      </p>

      <p>
        <strong>Text:</strong>
        <%= @for_select.text %>
      </p>

      <p>
        <strong>Grouper:</strong>
        <%= @for_select.grouper %>
      </p>

      <p>
        <strong>Option order:</strong>
        <%= @for_select.option_order %>
      </p>

      <p>
        <strong>Facility:</strong>
        <%= @for_select.facility %>
      </p>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_for_select_path(@for_select) %> |
<%= link_to 'Back', for_selects_path %>

app/views/keys/_form.html.erb
<%= form_for(@key, remote: true, format: :json, html: {class: :for_select_form}) do |f| %>
  <% if @key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
      <% @key.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel callout radius">
    <div id="divFacility">
      <%= f.label :facility %>
      <%#= f.text_field :facility %>
      <%= f.select(:facility, grouped_options_for_select(@grouped_options2), prompt: 'Please Select') %>
    </div>
    <div>
      <%= f.label :company %>
      <%#= f.text_field :company %>
      <%= f.select(:company, grouped_options_for_select(@grouped_options), prompt: 'Please Select') %>
    </div>
    <div>
      <%= f.label :description, 'Product' %>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.label :number, 'ID #' %>
      <%= f.text_field :number %>
    </div>
    <div>
      <%= f.label :checkout %>
      <%= f.date_field :checkout %>
    </div>
    <div>
      <%= f.label :checkin %>
      <%= f.date_field :checkin %>
    </div>
  </div> 

  <div class="row">
    <div class="small-6 columns">
      <%= f.submit(class: 'button tiny radius') %>
      <%#= f.submit 'Add / Update Company', :class => 'button tiny radius' %>
    </div>
    <div class="small-6 columns">
      <%= link_to("Cancel", "#", id: "bCancel", class: "button tiny radius") %>
    </div>       
  </div>

<% end %>

app/views/keys/_table.html.erb
<table>
  <thead>
    <tr class="tableHeader">
      <% if session[:role] == "admin2" %>
        <th><%= sort_link(@q, :facility, "Fac") %></th>
      <% end %>
      <th><%= sort_link(@q, :company) %></th>
      <th><%= sort_link(@q, :description, "Product") %></th>
      <th><%= sort_link(@q, :number, "ID #") %></th>
      <th><%= sort_link(@q, :checkout, "Checkout") %></th>
      <th><%= sort_link(@q, :checkin, "Checkin") %></th>
      <th></th>
      <% if session[:role] == "admin2" %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @keys.each do |key| %>
      <tr>
        <% if session[:role] == "admin2" %>
          <td><%= key.facility %></td>
        <% end %>
        <td><%= key.company %></td>
        <td><%= key.description %></td>
        <td><%= key.number %></td>
         <% unless key.checkout.blank? %>
          <td><%= key.checkout.strftime('%F') %></td>
        <% else %>
          <td> </td>
        <% end %>
        <% unless key.checkin.blank? %>
          <td colspan="5"><%= key.checkin.strftime('%F') %></td>
        <% else %>
          <td> </td>
        <% end %>

        <!-- <td><%#= link_to 'Show', key %></td> -->
        <td><%= link_to 'Edit', edit_key_path(key), class: 'lEdit', remote: true%></td>
        <% if session[:role] == "admin2" %>
          <td><%= link_to 'Destroy', key, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <td colspan="6" class="tableFooter">
        <%= paginate @keys %>
      </td>
      <td colspan="4" class="tableFooter">
        <%= @searchNumber %>  from <%= @totNumber %> total
      </td>
    </tr>
  </tbody> 
</table> 

app/views/keys/index.html.erb
<div class="row">
  <div class="large-6 large-centered columns alignCenterNoPadding">
    <h3>Company List  (Mid-Hudson)</h3>
  </div>
</div>

<div class="row">  
  <div class="large-9 columns">
    <div class="panel radius">
      <div class="panel callout radius">
              <%= search_form_for @q, id: 'fKey_filter', remote: true do |f| %>
          <div class="row collapse">

            <div class="hide">
              <div class="small-2 columns">
                <%= f.submit class: 'button tiny radius' %>           
              </div>
            </div>

            <div class="small-12 columns">
              <div class="row collapse">
                <div class="small-1 columns">
                  <%= f.label(:facility_eq, "Facility:", class: "right inline") %>
                </div>
                <div class="small-4 left columns">
                  <%= f.select(:facility_eq, grouped_options_for_select(@grouped_options2), prompt: 'Please Select') %>
                </div>
                <div class="small-2 columns">
                  <%= f.label(:company_eq, "Company:", class: "right inline")  %>
                </div>
                <div class="small-4 left columns">
                  <%#= f.search_field :company_cont %>
                  <%= f.select(:company_eq, grouped_options_for_select(@grouped_options), prompt: 'Please Select') %>
                </div>
              </div>

              <div class="row collapse">
                <div class="small-1 columns">
                  <%= f.label(:description_start, 'Product:', class: "right inline")  %>  
                </div>
                <div class="small-4 left columns">
                  <%= f.search_field :description_start %>
                </div>
                <div class="small-2 columns">
                  <%= f.label(:number_start, 'ID #:', class: "right inline")  %>  
                </div>
                <div class="small-2 left columns">
                  <%= f.search_field :number_start %>
                </div>

              </div>

              <div class="row collapse">
                <div class="small-1 columns">
                  <%= f.label(:checkout_gteq, 'Checkout:', class: "right inline")  %>  
                </div>
                <div class="small-4 left columns">
                  <%= f.date_field :checkout_gteq %>
                </div>
                <div class="small-2 columns">
                  <%= f.label(:checkin_lteq, 'Checkin:', class: "right inline")  %>  
                </div>
                <div class="small-4 left columns">
                  <%= f.date_field :checkin_lteq %>
                </div>
              </div>   
            </div>

          </div>
          
        <% end %>

      </div>
      <div id="divTable">
        <%= render('table') %>
      </div>
    </div>
  </div>
    <div class="large-3 columns">
      <div class="panel radius">
        <!-- <div class="panel callout radius"> -->
          <div class="large-centered">
              <%= link_to 'New Company', new_key_path, class: "button tiny radius", id: 'bNew', remote: true%>
          </div>
          <div id="divForm">
            <%#= render('form') %> 
          </div>
        <!-- </div> -->
      </div>
    </div>

<br>

</div>

app/views/keys/index.js.erb
$('#divTable').html("<%= j render('table') %>");

app/views/keys/new.html.erb
<h1>New key</h1>

<%= render 'form' %>

<%= link_to 'Back', keys_path %>

app/views/keys/new_edit.js.erb
// Insert new/edit form into divForm
	$('#divForm').html("<%= j render('form') %>");

// COMPANY VALUES
	// If "new" company will be nil, if edit will have a value
	var company = "<%=  @key.company %>"
	// alert(company.length)
	if (company.length > 0) {
		$('#key_company').val(company);
	};

//FACILITY VALUES
	var facility = "<%=  @key.facility %>"
	// Get users facility. If not admin2 set can only create new key for that facility
	var user_facility = "<%= session[:facility] %>"
	// Get role as non admin2 cannot change facility values
	var role = "<%= session[:role] %>" 
	// Get Facility name
	var facility_name = "<%= session[:facilityname] %>"
	

	if (role == 'admin2') {
		if (facility.length > 0) {
			$('#key_facility').val(facility);
		};
	} else {
		if (facility.length > 0) {
			$('#key_facility').val(facility).hide();
			$('#divFacility').append('&nbsp;&nbsp;&nbsp;&nbsp;'+facility_name);
		} else {
			$('#key_facility').val(user_facility).hide();
			$('#divFacility').append('&nbsp;&nbsp;&nbsp;&nbsp;'+facility_name);
		};
	};
	

	$('#bNew').hide();
	$('#bCancel').click(function(){
		// $('#scompany').appendTo('#divIndexHideWrapper');
		$('#divForm').html("");
		$('#bNew').show();
	});

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="large-3 columns panel radius">
    <div class="panel callout radius">
      <p>
        <strong>Facility:</strong>
        <%= @key.facility %>
      </p>
      <p>
        <strong>Company:</strong>
        <%= @key.company %>
      </p>
      <p>
        <strong>Product:</strong>
        <%= @key.description %>
      </p>
      <p>
        <strong>ID #:</strong>
        <%= @key.number %>
      </p>
      <p>
        <strong>Checkout:</strong>
        <%= @key.checkout %>
      </p>
      <p>
        <strong>Checkin:</strong>
        <%= @key.checkin %>
      </p>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>

app/views/keys/update_create.js.erb
$('#divForm').html("");
$('#bNew').show();

$('#fKey_filter').submit();

app/views/layouts/_header.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar>
    <section class="top-bar-section">
      <!-- Right Nav Section
      <ul class="right">
        <li class="has-dropdown">
          <a href="#">Rt Item 1</a>
          <ul class="dropdown">
            <li><a href="#">Drop 1</a></li>
            <li><a href="#">Drop 2</a></li>
            <li class="has-dropdown">
              <a href="#">Nested Drop</a>
              <ul class="dropdown">
                <li><a href="#">Nested 1</a></li>
                <li><a href="#">Nested 2</a></li>
                <li><a href="#">Nested 3</a></li>
              </ul>
            </li>
            <li><a href="#">Drop 3</a></li>
          </ul>
        </li>
        <li><a href="#">Rt Item 2</a></li>
      </ul> -->

      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to("For Select", for_selects_path) %></li>
        <li><%= link_to("Companies", keys_path) %></li>
        <li><%= link_to("Home", root_path) %></li>
      </ul>
    </section>
  </nav>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  	<title><%= content_for?(:title) ? yield(:title) : "Keys 2" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

	</head>
	<body>

  <!-- Having a container row allows control of the size of the site -->
    <div id="divContainer" class="row"><div class="large-12 columns">
      <%= render "layouts/header" %> 

      <%= yield %>
      <%= javascript_include_tag "application" %>
    </div></div> <!-- end div id="divContainer" -->


	</body>
</html>

app/views/static_pages/home.html.erb
<div class="row">
	
	<div id="static_pages_lt" class="large-8 columns">
		<h3>Welcome to <em>Ruby on Rails</em></h3>
		<div class="panel callout radius">
			<p>
				Key 2 Application
			</p>
		</div>
		<div class="panel radius">
			<h4>
			&nbsp;
			</h4>
		</div>
	</div>

	<div class="large-4 columns">
		<h4 class="subheader"><em>Key2</em> App</h4>
		<div class="panel radius">
			<h4>
			&nbsp;
			</h4>
		</div>
	</div>

</div>